#It will display a welcome message

echo "HELLO,WELCOME TO EMPLOYEE INFORMATION AND WAGE CALCULATION PROGRAM"

#BELOW CODE WILL CHECK IF EMPLOYEE PRESENT OR NOT
#UC1-Attendance_check

check=$((RANDOM%2))
if [ $check == 1 ]
then
	echo "EMPLOYEE IS PRESENT TODAY"
else
	echo "EMPLOYEE IS ABSENT TODAY"
fi


